# Generated by Django 3.1.2 on 2020-10-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nazwa')),
                ('content', models.CharField(max_length=250, verbose_name='opis aplikacji')),
                ('price', models.IntegerField(verbose_name='cena')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=100, verbose_name='link')),
            ],
        ),
    ]
